-- Supabase Database Setup Script
-- Execute este script no editor SQL do Supabase

-- Tabela de Convênios
CREATE TABLE IF NOT EXISTS convenios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Pacientes
CREATE TABLE IF NOT EXISTS pacientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  cpf VARCHAR(14),
  email VARCHAR(255),
  telefone VARCHAR(20),
  data_nascimento DATE,
  endereco TEXT,
  cidade VARCHAR(100),
  estado VARCHAR(2),
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Médicos
CREATE TABLE IF NOT EXISTS medicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  especialidade VARCHAR(255),
  crm VARCHAR(20),
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Agendamentos
CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id BIGINT REFERENCES pacientes(id),
  medico_id BIGINT REFERENCES medicos(id),
  convenio_id BIGINT REFERENCES convenios(id),
  data_hora TIMESTAMP WITH TIME ZONE NOT NULL,
  tipo_atendimento VARCHAR(100),
  status VARCHAR(50) DEFAULT 'pendente',
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Avaliações/Depoimentos
CREATE TABLE IF NOT EXISTS avaliacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_nome VARCHAR(255),
  comentario TEXT NOT NULL,
  nota INTEGER CHECK (nota >= 1 AND nota <= 5),
  aprovado BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir dados iniciais - Convênios
INSERT INTO convenios (nome) VALUES 
  ('Particular'),
  ('Unimed'),
  ('Amil'),
  ('Bradesco Saúde'),
  ('SulAmérica'),
  ('NotreDame Intermédica'),
  ('Porto Seguro'),
  ('Allianz')
ON CONFLICT DO NOTHING;

-- Inserir dados iniciais - Médicos
INSERT INTO medicos (nome, especialidade, crm) VALUES 
  ('Dra. Maria Santos', 'Ginecologia e Obstetrícia', 'CRM-SP 123456'),
  ('Dr. João Silva', 'Ginecologia', 'CRM-SP 234567')
ON CONFLICT DO NOTHING;

-- Habilitar Row Level Security (RLS)
ALTER TABLE convenios ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE avaliacoes ENABLE ROW LEVEL SECURITY;

-- Políticas RLS para acesso público (apenas leitura)
CREATE POLICY "Permitir leitura pública de convênios" ON convenios FOR SELECT USING (true);
CREATE POLICY "Permitir leitura pública de médicos" ON medicos FOR SELECT USING (true);
CREATE POLICY "Permitir leitura pública de avaliações aprovadas" ON avaliacoes FOR SELECT USING (aprovado = true);

-- Políticas para insert/update (pode ajustar conforme necessidade)
CREATE POLICY "Permitir insert em convênios" ON convenios FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir insert em pacientes" ON pacientes FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir insert em agendamentos" ON agendamentos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir insert em avaliações" ON avaliacoes FOR INSERT WITH CHECK (true);